### PR TITLE
Fixed test failure due to perl regression fix in 5.21.3

### PR DESCRIPTION
**Pull request by TBSliver**
Fix originally found and submitted in https://github.com/PadreIDE/Debug-Client/issues/2 - turned into Pull Request.

### CODE REVIEW

**Comment by TBSliver** [comment]
This will close #4 and should also close #2

**Comment by szabgab** [comment]
Thanks for the fix. There is not much maintenance going on around these modules, but I hope someone will soon be able to review your patch and apply it.

**Comment by TBSliver** [comment]
@szabgab no problem - do you know who would be best to poke for this?

Its not a complete rush, as got to look at the issues I found installing Padre itself after this fix, but its at least a start :) And it obviously doesnt look brilliant if the editor written in its own language doesnt work on the latest version.....

**Comment by manwar** [comment]
Thanks @TBSliver.

**Pull request merged**
